#!/bin/bash

CD=`pwd`

if [[ "$CD" =~ ^\/cygdrive.* ]]; then
	CD=`cygpath -w "$CD"`
fi

originalMungo="$CD/mungo-73dd8ae.jar"

mungoChecker="$CD/mungo-checker.jar"
mungoCheckerLib="$CD/mungo-checker-lib.jar"
mungoCheckerClass="org.checkerframework.checker.mungo.MungoChecker"

checkerVersion="3.3.0"
checker="$CD/checker-framework-$checkerVersion/checker/dist/checker.jar"

latexFolder="$CD/comparison/_latex"

if [ ! -f "$checker" ]; then
  echo "Comparison tests depend on the Checker Framework"
  echo "Did not find file $checker"
  exit 1
fi

tests=(
  "basic-checking"
  "boolean-decision"
  "state-refinement"
  "nullness-checking"
  "linearity-checking"
  "linearity-checking-corner-cases"
  "protocol-completion"
  "protocol-completion-corner-cases"
  "class-analysis"
  "class-analysis-2"
  "droppable-objects"
  "generics"
  "auction"
  "file-1"
  "iterator-attempt1"
  "iterator-attempt2"
  "iterator-attempt3"
  "iterator-attempt4"
  "iterator-attempt5"
  "iterator-attempt6"
  "iterator-attempt7"
  "original-mungo-flow-issue-1"
  "original-mungo-flow-issue-2"
  "original-mungo-crash-1"
  "original-mungo-crash-2"
  "original-mungo-crash-3"
  "original-mungo-crash-1-adapted"
  "original-mungo-crash-2-adapted"
  "original-mungo-crash-3-adapted"
)

mkdir -p "$latexFolder"

latexCode="\\\\lstset{language=,caption=\\\\textit{%s}}\n\\\\begin{code}\n%s\\\\end{code}\n\n"
latexJavaCode="\\\\lstset{language=Java,caption=\\\\textit{%s}}\n\\\\begin{code}\n%s\\\\end{code}\n\n"
latexOutput1="\\\\lstset{language=,caption=Original Mungo output}\n\\\\begin{code}\n%s\\\\end{code}\n\n"
latexOutput2="\\\\lstset{language=,caption=New Mungo output}\n\\\\begin{code}\n%s\\\\end{code}\n\n"

for testName in "${tests[@]}"
do
  cd "comparison/$testName"
  echo "Running test: $testName"
  output1=`java -jar "$originalMungo" -classpath "$originalMungo;$mungoCheckerLib" *.java 2>&1`
  output2=`java -jar "$checker" -classpath "$mungoChecker" -processor "$mungoCheckerClass" *.java 2>&1`
  
  printf "## Original Mungo's output\n\n\`\`\`\n%s\`\`\`\n\n" "$output1" > README.md
  printf "## Mungo Checker's output\n\n\`\`\`\n%s\`\`\`\n" "$output2" >> README.md

  latexFile="$latexFolder/$testName.tex"
  printf "" > "$latexFile"
  
  shopt -s nullglob
  for file in *.protocol
  do
    contents=`cat "$file"`
    printf "$latexCode" "$file" "$contents" >> "$latexFile"
  done
  
  shopt -s nullglob
  for file in *.java
  do
    contents=`cat "$file"`
    printf "$latexJavaCode" "$file" "$contents" >> "$latexFile"
  done
  
  if [[ "$output1" == "" ]]; then
    output1=$'None\n'
  fi
  
  if [[ "$output2" == "" ]]; then
    output2=$'None\n'
  fi
  
  printf "$latexOutput1" "$output1" >> "$latexFile"
  printf "$latexOutput2" "$output2" >> "$latexFile"
  
  cd "$CD"
done
