#!/bin/bash

CD=`pwd`

if [[ "$CD" =~ ^\/cygdrive.* ]]; then
	CD=`cygpath -w "$CD"`
fi

#originalMungo="$CD/mungo-73dd8ae.jar"
originalMungo="$CD/mungo-tools-4d05a7.jar"

testsFolder="$CD/to_mungo_devs"

tests=(
  "flow-issue-1"
  "flow-issue-2"
  "crash-1"
  "crash-2"
  "crash-3"
  "crash-1-adapted"
  "crash-2-adapted"
  "crash-3-adapted"
)

for testName in "${tests[@]}"
do
  cd "$testsFolder/$testName"
  echo "Running test: $testName"
  output=`java -jar "$originalMungo" -classpath "$originalMungo" *.java 2>&1`
  
  printf "## Current Mungo's output\n\n\`\`\`\n%s\`\`\`\n\n" "$output" > README.md
  
  cd "$CD"
done
