#!/bin/bash

CD=`pwd`

if [[ "$CD" =~ ^\/cygdrive.* ]]; then
	CD=`cygpath -w "$CD"`
fi

#originalMungo="$CD/mungo-73dd8ae.jar"
originalMungo="$CD/mungo-tools-4d05a7.jar"

mungoChecker="$CD/mungo-checker.jar"
mungoCheckerLib="$CD/mungo-checker-lib.jar"
mungoCheckerClass="org.checkerframework.checker.mungo.MungoChecker"

checkerVersion="3.6.1"
checker="$CD/checker-framework-$checkerVersion/checker/dist/checker.jar"

if [ ! -f "$checker" ]; then
  echo "Comparison tests depend on the Checker Framework"
  echo "Did not find file $checker"
  exit 1
fi

tests=(
  "../tests/linearity"
)

for test in "${tests[@]}"
do
  cd "$test"
  echo "Running test: $test"
  
  printf "## Original Mungo's output\n\n\`\`\`\n" > Results.md
  
  shopt -s nullglob
  for file in *.java
  do
    output1=`java -jar "$originalMungo" -classpath "$originalMungo;$mungoCheckerLib" "$file" Obj.java 2>&1`
    printf "%s" "$output1" >> Results.md
  done
  
  printf "\`\`\`\n\n" >> Results.md

  output2=`java -jar "$checker" -classpath "$mungoChecker" -processor "$mungoCheckerClass" *.java 2>&1`
  printf "## Mungo Checker's output\n\n\`\`\`\n%s\`\`\`\n" "$output2" >> Results.md
  
  cd "$CD"
done
