#!/bin/bash

CD=`pwd`

if [[ "$CD" =~ ^\/cygdrive.* ]]; then
	CD=`cygpath -w "$CD"`
fi

mungoJar="$CD/mungo-73dd8ae.jar"

javaTypestateChecker="$CD/../dist/jtc-checker.jar"
javaTypestateCheckerLib="$CD/../dist/jtc-checker-lib.jar"
javaTypestateCheckerClass="org.checkerframework.checker.jtc.JavaTypestateChecker"

checkerVersion="3.8.0"

checker="$CD/../dist/checker-framework-$checkerVersion/checker/dist/checker.jar"

if [ ! -f "$checker" ]; then
  echo "Comparison tests depend on the Checker Framework"
  echo "Did not find file $checker"
  exit 1
fi

tests=(
  "../tests/linearity"
)

for test in "${tests[@]}"
do
  cd "$test"
  echo "Running test: $test"

  printf "## Mungo's output\n\n\`\`\`\n" > Results.md

  shopt -s nullglob
  for file in *.java
  do
    output1=`java -jar "$mungoJar" -classpath "$mungoJar;$javaTypestateCheckerLib" "$file" Obj.java 2>&1`
    printf "%s" "$output1" >> Results.md
  done

  printf "\`\`\`\n\n" >> Results.md

  output2=`java -jar "$checker" -classpath "$javaTypestateChecker" -processor "$javaTypestateCheckerClass" *.java 2>&1`
  printf "## Java Typestate Checker's output\n\n\`\`\`\n%s\`\`\`\n" "$output2" >> Results.md

  cd "$CD"
done
