package demos.SMTP.TranslatedSMTP;

/**
 * Generated by StMungo
 * Thu Apr 23 18:59:34 BST 2020
 */
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import java.lang.String;

public class CMain {
    public static String safeRead(BufferedReader readerC) {
        String readline = "";
        try {
            readline = readerC.readLine();
        } catch(IOException e) {
            System.out.println("Input/Output error, unable to read");
            System.exit(-1);
        }
        return readline;
    }

    public static void main(String[] args) {
        // Create the current role
        CRole currentC =  new CRole();
        // readerC can be used to input strings, and then use them in send method invocation
        BufferedReader readerC = new BufferedReader(new InputStreamReader(System.in));
        // Method invocation follows the C typestate
        String payload1 = currentC.receive_220StringFromS();
        System.out.println("Received from S: " + payload1);
        System.out.print("Choose a label among [EHLO, QUIT]: ");
        String sread1 = safeRead(readerC);
        switch(sread1){
            case "EHLO":
                currentC.send_EHLOToS();
                System.out.print("Send to S: ");
                String payload3 = safeRead(readerC);
                currentC.send_ehloStringToS(payload3);
                _X: do{
                    switch(currentC.receive_CChoice1LabelFromS()) {
                        case _250DASH:
                            String payload5 = currentC.receive_250dashStringFromS();
                            System.out.println("Received from S: " + payload5);
                            continue _X;
                        case _250:
                            String payload7 = currentC.receive_250StringFromS();
                            System.out.println("Received from S: " + payload7);
                            System.out.print("Choose a label among [STARTTLS, QUIT]: ");
                            String sread2 = safeRead(readerC);
                            switch(sread2){
                                case "STARTTLS":
                                    currentC.send_STARTTLSToS();
                                    System.out.print("Send to S: ");
                                    String payload9 = safeRead(readerC);
                                    currentC.send_starttlsStringToS(payload9);
                                    String payload11 = currentC.receive_220StringFromS();
                                    System.out.println("Received from S: " + payload11);
                                    System.out.print("Choose a label among [EHLO, QUIT]: ");
                                    String sread3 = safeRead(readerC);
                                    switch(sread3){
                                        case "EHLO":
                                            currentC.send_EHLOToS();
                                            System.out.print("Send to S: ");
                                            String payload13 = safeRead(readerC);
                                            currentC.send_ehloStringToS(payload13);
                                            _X1: do{
                                                switch(currentC.receive_CChoice1LabelFromS()) {
                                                    case _250DASH:
                                                        String payload15 = currentC.receive_250dashStringFromS();
                                                        System.out.println("Received from S: " + payload15);
                                                        continue _X1;
                                                    case _250:
                                                        String payload17 = currentC.receive_250StringFromS();
                                                        System.out.println("Received from S: " + payload17);
                                                        _Y: do{
                                                            System.out.print("Choose a label among [AUTH, QUIT]: ");
                                                            String sread4 = safeRead(readerC);
                                                            switch(sread4){
                                                                case "AUTH":
                                                                    currentC.send_AUTHToS();
                                                                    System.out.print("Send to S: ");
                                                                    String payload19 = safeRead(readerC);
                                                                    currentC.send_authStringToS(payload19);
                                                                    switch(currentC.receive_CChoice2LabelFromS()) {
                                                                        case _235:
                                                                            String payload21 = currentC.receive_235StringFromS();
                                                                            System.out.println("Received from S: " + payload21);
                                                                            _Z1: do{
                                                                                System.out.print("Choose a label among [MAIL, QUIT]: ");
                                                                                String sread5 = safeRead(readerC);
                                                                                switch(sread5){
                                                                                    case "MAIL":
                                                                                        currentC.send_MAILToS();
                                                                                        System.out.print("Send to S: ");
                                                                                        String payload23 = safeRead(readerC);
                                                                                        currentC.send_mailStringToS(payload23);
                                                                                        switch(currentC.receive_CChoice3LabelFromS()) {
                                                                                            case _501:
                                                                                                String payload25 = currentC.receive_501StringFromS();
                                                                                                System.out.println("Received from S: " + payload25);
                                                                                                continue _Z1;
                                                                                            case _250:
                                                                                                String payload27 = currentC.receive_250StringFromS();
                                                                                                System.out.println("Received from S: " + payload27);
                                                                                                _Z2: do{
                                                                                                    System.out.print("Choose a label among [RCPT, DATA]: ");
                                                                                                    String sread6 = safeRead(readerC);
                                                                                                    switch(sread6){
                                                                                                        case "RCPT":
                                                                                                            currentC.send_RCPTToS();
                                                                                                            System.out.print("Send to S: ");
                                                                                                            String payload29 = safeRead(readerC);
                                                                                                            currentC.send_rcptStringToS(payload29);
                                                                                                            switch(currentC.receive_CChoice4LabelFromS()) {
                                                                                                                case _250:
                                                                                                                    String payload31 = currentC.receive_250StringFromS();
                                                                                                                    System.out.println("Received from S: " + payload31);
                                                                                                                    continue _Z2;
                                                                                                            }
                                                                                                            break _Z2;
                                                                                                        case "DATA":
                                                                                                            currentC.send_DATAToS();
                                                                                                            System.out.print("Send to S: ");
                                                                                                            String payload33 = safeRead(readerC);
                                                                                                            currentC.send_dataStringToS(payload33);
                                                                                                            String payload35 = currentC.receive_354StringFromS();
                                                                                                            System.out.println("Received from S: " + payload35);
                                                                                                            _Z3: do{
                                                                                                                System.out.print("Choose a label among [DATALINE, SUBJECT, ATAD]: ");
                                                                                                                String sread7 = safeRead(readerC);
                                                                                                                switch(sread7){
                                                                                                                    case "DATALINE":
                                                                                                                        currentC.send_DATALINEToS();
                                                                                                                        System.out.print("Send to S: ");
                                                                                                                        String payload37 = safeRead(readerC);
                                                                                                                        currentC.send_datalineStringToS(payload37);
                                                                                                                        continue _Z3;
                                                                                                                    case "SUBJECT":
                                                                                                                        currentC.send_SUBJECTToS();
                                                                                                                        System.out.print("Send to S: ");
                                                                                                                        String payload39 = safeRead(readerC);
                                                                                                                        currentC.send_subjectStringToS(payload39);
                                                                                                                        continue _Z3;
                                                                                                                    case "ATAD":
                                                                                                                        currentC.send_ATADToS();
                                                                                                                        System.out.print("Send to S: ");
                                                                                                                        String payload41 = safeRead(readerC);
                                                                                                                        currentC.send_atadStringToS(payload41);
                                                                                                                        String payload43 = currentC.receive_250StringFromS();
                                                                                                                        System.out.println("Received from S: " + payload43);
                                                                                                                        continue _Z1;
                                                                                                                }
                                                                                                            } while(true);
                                                                                                        }
                                                                                                    } while(true);
                                                                                                }
                                                                                                break _Z1;
                                                                                            case "QUIT":
                                                                                                currentC.send_QUITToS();
                                                                                                System.out.print("Send to S: ");
                                                                                                String payload45 = safeRead(readerC);
                                                                                                currentC.send_quitStringToS(payload45);
                                                                                                break _Z1;
                                                                                        }
                                                                                    } while(true);
                                                                                    break _Y;
                                                                                case _535:
                                                                                    String payload47 = currentC.receive_535StringFromS();
                                                                                    System.out.println("Received from S: " + payload47);
                                                                                    continue _Y;
                                                                            }
                                                                            break _Y;
                                                                        case "QUIT":
                                                                            currentC.send_QUITToS();
                                                                            System.out.print("Send to S: ");
                                                                            String payload49 = safeRead(readerC);
                                                                            currentC.send_quitStringToS(payload49);
                                                                            break _Y;
                                                                    }
                                                                } while(true);
                                                                break _X1;
                                                        }
                                                    } while(true);
                                                    break _X;
                                                case "QUIT":
                                                    currentC.send_QUITToS();
                                                    System.out.print("Send to S: ");
                                                    String payload51 = safeRead(readerC);
                                                    currentC.send_quitStringToS(payload51);
                                                    break _X;
                                            }
                                            break _X;
                                        case "QUIT":
                                            currentC.send_QUITToS();
                                            System.out.print("Send to S: ");
                                            String payload53 = safeRead(readerC);
                                            currentC.send_quitStringToS(payload53);
                                            break _X;
                                    }
                                    break _X;
                            }
                        } while(true);
                        break;
                    case "QUIT":
                        currentC.send_QUITToS();
                        System.out.print("Send to S: ");
                        String payload55 = safeRead(readerC);
                        currentC.send_quitStringToS(payload55);
                        break;
                }
            }
        }
