package demos.SMTP.TranslatedSMTP;

/**
 * Generated by StMungo
 * Thu Apr 23 18:59:36 BST 2020
 */
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import java.lang.String;

public class SMain {
    public static String safeRead(BufferedReader readerS) {
        String readline = "";
        try {
            readline = readerS.readLine();
        } catch(IOException e) {
            System.out.println("Input/Output error, unable to read");
            System.exit(-1);
        }
        return readline;
    }

    public static void main(String[] args) {
        // Create the current role
        SRole currentS =  new SRole();
        // readerS can be used to input strings, and then use them in send method invocation
        BufferedReader readerS = new BufferedReader(new InputStreamReader(System.in));
        // Method invocation follows the S typestate
        System.out.print("Send to C: ");
        String payload1 = safeRead(readerS);
        currentS.send_220StringToC(payload1);
        switch(currentS.receive_SChoice1LabelFromC()) {
            case EHLO:
                String payload3 = currentS.receive_ehloStringFromC();
                System.out.println("Received from C: " + payload3);
                _X: do{
                    System.out.print("Choose a label among [_250DASH, _250]: ");
                    String sread1 = safeRead(readerS);
                    switch(sread1){
                        case "_250DASH":
                            currentS.send_250DASHToC();
                            System.out.print("Send to C: ");
                            String payload5 = safeRead(readerS);
                            currentS.send_250dashStringToC(payload5);
                            continue _X;
                        case "_250":
                            currentS.send_250ToC();
                            System.out.print("Send to C: ");
                            String payload7 = safeRead(readerS);
                            currentS.send_250StringToC(payload7);
                            switch(currentS.receive_SChoice2LabelFromC()) {
                                case STARTTLS:
                                    String payload9 = currentS.receive_starttlsStringFromC();
                                    System.out.println("Received from C: " + payload9);
                                    System.out.print("Send to C: ");
                                    String payload11 = safeRead(readerS);
                                    currentS.send_220StringToC(payload11);
                                    switch(currentS.receive_SChoice1LabelFromC()) {
                                        case EHLO:
                                            String payload13 = currentS.receive_ehloStringFromC();
                                            System.out.println("Received from C: " + payload13);
                                            _X1: do{
                                                System.out.print("Choose a label among [_250DASH, _250]: ");
                                                String sread2 = safeRead(readerS);
                                                switch(sread2){
                                                    case "_250DASH":
                                                        currentS.send_250DASHToC();
                                                        System.out.print("Send to C: ");
                                                        String payload15 = safeRead(readerS);
                                                        currentS.send_250dashStringToC(payload15);
                                                        continue _X1;
                                                    case "_250":
                                                        currentS.send_250ToC();
                                                        System.out.print("Send to C: ");
                                                        String payload17 = safeRead(readerS);
                                                        currentS.send_250StringToC(payload17);
                                                        _Y: do{
                                                            switch(currentS.receive_SChoice3LabelFromC()) {
                                                                case AUTH:
                                                                    String payload19 = currentS.receive_authStringFromC();
                                                                    System.out.println("Received from C: " + payload19);
                                                                    System.out.print("Choose a label among [_235, _535]: ");
                                                                    String sread3 = safeRead(readerS);
                                                                    switch(sread3){
                                                                        case "_235":
                                                                            currentS.send_235ToC();
                                                                            System.out.print("Send to C: ");
                                                                            String payload21 = safeRead(readerS);
                                                                            currentS.send_235StringToC(payload21);
                                                                            _Z1: do{
                                                                                switch(currentS.receive_SChoice4LabelFromC()) {
                                                                                    case MAIL:
                                                                                        String payload23 = currentS.receive_mailStringFromC();
                                                                                        System.out.println("Received from C: " + payload23);
                                                                                        System.out.print("Choose a label among [_501, _250]: ");
                                                                                        String sread4 = safeRead(readerS);
                                                                                        switch(sread4){
                                                                                            case "_501":
                                                                                                currentS.send_501ToC();
                                                                                                System.out.print("Send to C: ");
                                                                                                String payload25 = safeRead(readerS);
                                                                                                currentS.send_501StringToC(payload25);
                                                                                                continue _Z1;
                                                                                            case "_250":
                                                                                                currentS.send_250ToC();
                                                                                                System.out.print("Send to C: ");
                                                                                                String payload27 = safeRead(readerS);
                                                                                                currentS.send_250StringToC(payload27);
                                                                                                _Z2: do{
                                                                                                    switch(currentS.receive_SChoice5LabelFromC()) {
                                                                                                        case RCPT:
                                                                                                            String payload29 = currentS.receive_rcptStringFromC();
                                                                                                            System.out.println("Received from C: " + payload29);
                                                                                                            System.out.print("Choose a label among [_250]: ");
                                                                                                            String sread5 = safeRead(readerS);
                                                                                                            switch(sread5){
                                                                                                                case "_250":
                                                                                                                    currentS.send_250ToC();
                                                                                                                    System.out.print("Send to C: ");
                                                                                                                    String payload31 = safeRead(readerS);
                                                                                                                    currentS.send_250StringToC(payload31);
                                                                                                                    continue _Z2;
                                                                                                            }
                                                                                                            break _Z2;
                                                                                                        case DATA:
                                                                                                            String payload33 = currentS.receive_dataStringFromC();
                                                                                                            System.out.println("Received from C: " + payload33);
                                                                                                            System.out.print("Send to C: ");
                                                                                                            String payload35 = safeRead(readerS);
                                                                                                            currentS.send_354StringToC(payload35);
                                                                                                            _Z3: do{
                                                                                                                switch(currentS.receive_SChoice6LabelFromC()) {
                                                                                                                    case DATALINE:
                                                                                                                        String payload37 = currentS.receive_datalineStringFromC();
                                                                                                                        System.out.println("Received from C: " + payload37);
                                                                                                                        continue _Z3;
                                                                                                                    case SUBJECT:
                                                                                                                        String payload39 = currentS.receive_subjectStringFromC();
                                                                                                                        System.out.println("Received from C: " + payload39);
                                                                                                                        continue _Z3;
                                                                                                                    case ATAD:
                                                                                                                        String payload41 = currentS.receive_atadStringFromC();
                                                                                                                        System.out.println("Received from C: " + payload41);
                                                                                                                        System.out.print("Send to C: ");
                                                                                                                        String payload43 = safeRead(readerS);
                                                                                                                        currentS.send_250StringToC(payload43);
                                                                                                                        continue _Z1;
                                                                                                                }
                                                                                                            } while(true);
                                                                                                        }
                                                                                                    } while(true);
                                                                                                }
                                                                                                break _Z1;
                                                                                            case QUIT:
                                                                                                String payload45 = currentS.receive_quitStringFromC();
                                                                                                System.out.println("Received from C: " + payload45);
                                                                                                break _Z1;
                                                                                        }
                                                                                    } while(true);
                                                                                    break _Y;
                                                                                case "_535":
                                                                                    currentS.send_535ToC();
                                                                                    System.out.print("Send to C: ");
                                                                                    String payload47 = safeRead(readerS);
                                                                                    currentS.send_535StringToC(payload47);
                                                                                    continue _Y;
                                                                            }
                                                                            break _Y;
                                                                        case QUIT:
                                                                            String payload49 = currentS.receive_quitStringFromC();
                                                                            System.out.println("Received from C: " + payload49);
                                                                            break _Y;
                                                                    }
                                                                } while(true);
                                                                break _X1;
                                                        }
                                                    } while(true);
                                                    break _X;
                                                case QUIT:
                                                    String payload51 = currentS.receive_quitStringFromC();
                                                    System.out.println("Received from C: " + payload51);
                                                    break _X;
                                            }
                                            break _X;
                                        case QUIT:
                                            String payload53 = currentS.receive_quitStringFromC();
                                            System.out.println("Received from C: " + payload53);
                                            break _X;
                                    }
                                    break _X;
                            }
                        } while(true);
                        break;
                    case QUIT:
                        String payload55 = currentS.receive_quitStringFromC();
                        System.out.println("Received from C: " + payload55);
                        break;
                }
            }
        }
