package demos.Adder;

/**
 * Generated by StMungo
 * Tue Apr 14 17:42:10 BST 2020
 */
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class SMain {
    public static String safeRead(BufferedReader readerS) {
        String readline = "";
        try {
            readline = readerS.readLine();
        } catch(IOException e) {
            System.out.println("Input/Output error, unable to read");
            System.exit(-1);
        }
        return readline;
    }

    public static void main(String[] args) {
        // Create the current role
        SRole currentS =  new SRole();
        // readerS can be used to input strings, and then use them in send method invocation
        BufferedReader readerS = new BufferedReader(new InputStreamReader(System.in));
        // Method invocation follows the S typestate
        _X: do{
            switch(currentS.receive_SChoice1LabelFromC()) {
                case ADD:
                    Integer payload1 = currentS.receive_AddintFromC();
                    System.out.println("Received from C: " + payload1);
                    Integer payload2 = currentS.receive_AddintFromC();
                    System.out.println("Received from C: " + payload2);
                    System.out.print("Send to C: ");
                    Integer payload3 = Integer.parseInt(safeRead(readerS));
                    currentS.send_ResintToC(payload3);
                    continue _X;
                case BYE:
                    currentS.receive_ByeFromC();
                    continue _X;
            }
        } while(true);
    }
}
